library(shiny); library(reshape2); library(ICC); library(ggplot2); library(ggridges); library(expss); library(shinyalert); library(shinyBS); library(kableExtra); library(tibble); library(shinyscreenshot)

ui <-fluidPage(
  img(src="FishSampling.png", height = 200/2, width = 715/2),
  #img(src="QR code.png", height = 150, width = 150),
  navbarPage("",
             tabPanel(strong("HOME"),                      
                      p(""),
                      strong("This tool informs fish sampling strategies, we present an open web-based application which estimates sampling accuracy related to sea louse abundance, given inputs (such as presumed abundance or clustering effect) provided by the user."),
                      p(""),
                      img(src="salmon farm.png", height = 500/2, width = 715/2),
                      p(""),
                      strong("Scenario 1. How probable does the estimated abundance through sampling fall within a certain range?"),
                      tags$i("   Example usage: to figure out the overall accuracy of esatimated abundance"),
                      p(""),
                      strong("Scenario 2. How probable is abundance estimated to be higher than a certain level of abundance?"),
                      tags$i("   Example usage: to determine if abundance is over the lice limit or treatment threshold"),
                      p(""),
                      strong("Scenario 3. How probable is the relative difference between the two abundances correctly determined?"),
                      tags$i("   Example usage: to confirm the difference in abundance between before treatment and after treatment"),
                      p(""),
                      img(src="UPEI Logo_no background.png", height = 130/3, width = 270/3),
                      img(src="CERC.png", height = 100/3, width = 270/3),
                      img(src="ofi.jpg", height = 130/3, width = 270/3),
                      p("Please send any comments, questions or suggestions to Jaewoon Jeong (jjeong@upei.ca)"),
                      p(""),
                      p("R shiny code is available from here, https://github.com/jaewoonjeong/FishSampling")),
             
             tabPanel(strong("SCENARIO 1"), 
                      titlePanel("Accuracy of estimated abundance"),
                      fluidPage(column(2,radioButtons("clustering1", "Clustering Effect:",c(No = "no", Yes = "yes"))),
                        column(2,numericInput("iteration1","Iteration",value=10,min=1,max=100000))),
                      conditionalPanel(condition = "input.clustering1 == 'no'",div(HTML("<b>Total number of fish (A)</b> are sampled from a farm with <b>an assumed true abundance (B)</b>. <b><u>The output is the probability</b></u> that the abundance estimated through this sampling will fall between <b>the lower limit (F1) and upper limit (F2)</b>."))),
                      conditionalPanel(condition = "input.clustering1 == 'yes'",div(HTML("<b>Total number of fish (A)</b> are sampled from a farm consisting of <b>(D) a certain number of pens</b> with <b>an assumed true abundances (B)</b>. The fish are sampled from <b>selected numbers of pens (C)</b>. <b><u>The output is the probability</b></u> that the abundance estimated through this sampling will fall between <b>the lower limit (F1) and upper limit (F2)</b>."))),
                      p(""),
                      sidebarLayout(sidebarPanel(width=5,fluidRow(
                          column(6,
                                 selectInput("TSS1", "(A) Total number of sampled fish from a farm:",choices = 1:1000,selected=c(60),multiple = TRUE),
                                 numericInput("ab1", "(B) Assumed True Abundance:", value = 3.0, min=0, max=100, step=0.01)),
                          column(6,
                                 conditionalPanel(condition = "input.clustering1 == 'yes'",selectInput("choice1", "(C) Numbers of selected pens for sampling:", choices =1:20,selected=c(3,5,10), multiple = TRUE)),
                                 conditionalPanel(condition = "input.clustering1 == 'yes'",sliderInput("pen1", "(D) Total Number of pens in a farm:", value=10, min=2, max=20)),
                                 conditionalPanel(condition = "input.clustering1 == 'yes'",sliderInput("icc1", "(E) ICC:", value=0.01, min=0.01, max=0.35,step = 0.01)))),
                          fluidRow(
                            column(6,numericInput("l.m","(F1) Lower Limit:",2.7,min=0,max=10,step=0.01)),
                          column(6,numericInput("u.m","(F2) Upper Limit:",3.3,min=0,max=10,step=0.01)),
                          conditionalPanel(condition = "input.clustering1 == 'yes'",plotOutput("Plot.1B.2", height = "300px")),
                          conditionalPanel(condition = "input.clustering1 == 'yes'",h4("")))),
                        mainPanel(width=7,
                          actionButton("goButton1", "Go!", class = "btn-primary"),
                          h1(""),
                          conditionalPanel(condition = "input.clustering1 == 'no'",div(HTML("<b><u>Probability of estimating the abundance between the lower and upper limits </b></u>"))),
                          conditionalPanel(condition = "input.clustering1 == 'yes'",div(HTML("<b><u>Probability of estimating the abundance between the lower and upper limits </b></u>and<i> (Number of sampled fish per pen)</i>"))),
                          htmlOutput("Table.1.1"),conditionalPanel(condition = "input.clustering1 == 'yes'",useShinyalert(), actionButton("btn1.2", "?")),
                          h1(""),
                          plotOutput("Plot1"),useShinyalert(),actionButton("btn1.3", "?"),
                          h1(""),
                          actionButton("go1", "Take a screenshot")))),
             
             tabPanel(strong("SCENARIO 2"), 
                      titlePanel("Comparison of an estimated abundance with a certain level of abundance"),
                      fluidPage(column(2,radioButtons("clustering3", "Clustering Effect:",c(No = "no", Yes = "yes"))),
                        column(2,numericInput("iteration3","Iteration",value=10,min=1,max=100000))),
                      conditionalPanel(condition = "input.clustering3 == 'no'",div(HTML("<b>Total number of fish (A)</b> are sampled from a farm with <b>an assumed true abundance (B)</b>. <b><u>The output is the probability</b></u> that the abundance estimated through this sampling will be higher than <b>a certain level of abundance (F)</b>."))),
                      conditionalPanel(condition = "input.clustering3 == 'yes'",div(HTML("<b>Total number of fish (A)</b> are sampled from a farm consisting of <b>(D) a certain number of pens</b> with <b>an assumed true abundance (B)</b>. The fish are sampled from <b>selected numbers of pens (C)</b>. <b><u>The output is the probability</b></u> that the abundance estimated through this sampling will be higher than <b>a certain level of abundance (F)</b>."))),
                      p(""),
                      sidebarLayout(sidebarPanel(width=5,fluidRow(
                          column(6,
                                 selectInput("TSS3", "(A) Total number of  fish to sample from a farm:",choices = 1:1000,selected=c(60),multiple = TRUE),
                                 numericInput("ab3", "(B) Assumed True Abundance:", value =2.6, min=0, max=10, step=0.01),
                                 numericInput("th3","(F) Certain level of abundance:",value=3,min=0,max=10,step=0.01)),
                          column(6,
                                 conditionalPanel(condition = "input.clustering3 == 'yes'",selectInput("choice3", "(C) Numbers of selected pens for sampling:",choices =1:20,selected=c(3,5,10),multiple = TRUE)),
                                 conditionalPanel(condition = "input.clustering3 == 'yes'",sliderInput("pen3", "(D) Number of pens in a farm:", value=10, min=2, max=20)),
                                 conditionalPanel(condition = "input.clustering3 == 'yes'",sliderInput("icc3", "(E) ICC:", value=0.01, min=0.01, max=0.35,step = 0.01)))),
                          conditionalPanel(condition = "input.clustering3 == 'yes'",plotOutput("Plot.3B.2", height = "300px")),
                          conditionalPanel(condition = "input.clustering3 == 'yes'",h4(""))),
                        mainPanel(width=7,
                          actionButton("goButton3", "Go!", class = "btn-primary"),
                          h1(""),
                          conditionalPanel(condition = "input.clustering3 == 'no'",div(HTML("<b><u>Probability of estimating abundance higher than the certain level of abundance </b></u>"))),
                          conditionalPanel(condition = "input.clustering3 == 'yes'",div(HTML("<b><u>Probability of estimating abundance higher than the certain level of abundance </b></u>and<i> (Number of sampled fish per pen)</i>"))),
                          htmlOutput("Table.3.1"),conditionalPanel(condition = "input.clustering3 == 'yes'",useShinyalert(),   actionButton("btn2.2", "?")),
                          h1(""),
                          plotOutput("Plot3"),useShinyalert(),  actionButton("btn2.3", "?"),
                          h1(""),
                          actionButton("go2", "Take a screenshot")))),
             
             tabPanel(strong("SCENARIO 3"), 
                      titlePanel("Comparison of two abundances"),
                      fluidPage(column(2, radioButtons("clustering2", "Clustering Effect:",c(No = "no", Yes = "yes"))),
                        column(2, numericInput("iteration2","Iteration",value=10,min=1,max=100000))),
                      conditionalPanel(condition = "input.clustering2 == 'no'",div(HTML("<b>Total number of fish (A)</b> are sampled from each of two farms with <b>assumed true (lower) Abundance1 (B) and (higher) Abundance2 (F)</b>. <b><u>The output is the probability</b></u> that this sampling will determine that Abundance1 (B) is lower than Abundance2 (F)."))),
                      conditionalPanel(condition = "input.clustering2 == 'yes'",div(HTML("<b>Total number of fish (A)</b> are sampled from each of two farms consisting of <b>(D) a certain number of pens</b> with <b>assumed true (lower) Abundance1 (B) and (higher) Abundance2 (F)</b>. The fish are sampled from <b> selected numbers of pens (C)</b>. <b><u>The output is the probability</b></u> that this sampling will determine that Abundance1 (B) is lower than Abundance2 (F)."))),
                      p(""),
                      sidebarLayout(sidebarPanel(width=5,fluidRow(
                          column(6,
                                 selectInput("TSS2","(A) Total number of sampled fish from each farm:",choices=1:1000,selected=c(60),multiple=TRUE),
                                 numericInput("ab1.2B", "(B) Assumed True (lower) Abundance1:", value =1.3, min=0, max=10, step=0.01),
                                 numericInput("ab2.2B", "(F) Assumed True (higher) Abundance2:", value =1.7, min=0, max=10, step=0.01)),
                          column(6,
                                 conditionalPanel(condition = "input.clustering2 == 'yes'",selectInput("choice2", "(C) Numbers of selected pens for sampling:", choices =1:20,selected=c(3,5,10), multiple = TRUE)),
                                 conditionalPanel(condition = "input.clustering2 == 'yes'",sliderInput("pen2", "(D) Total Number of pens in a farm:", value=10, min=2, max=20)),
                                 conditionalPanel(condition = "input.clustering2 == 'yes'",sliderInput("icc1.2B", "(E-1) ICC1:", value=0.01, min=0.01, max=0.35,step = 0.01)),
                                 conditionalPanel(condition = "input.clustering2 == 'yes'",sliderInput("icc2.2B", "(E-2) ICC2:", value=0.01, min=0.01, max=0.35,step = 0.01)))),
                          conditionalPanel(condition = "input.clustering2 == 'yes'",plotOutput("Plot.2B.1", height = "300px")),
                          conditionalPanel(condition = "input.clustering2 == 'yes'",h4(""))),
                        mainPanel(width=7,
                          actionButton("goButton2", "Go!", class = "btn-primary"),
                          h1(""),
                         conditionalPanel(condition = "input.clustering2 == 'no'",div(HTML("<b><u>Probability of determining that Abundance1 is lower than Abundance2</b></u>"))),
                         conditionalPanel(condition = "input.clustering2 == 'yes'",div(HTML("<b><u>Probability of determining that Abundance1 is lower than Abundance2</b></u> and<i> (Number of sampled fish per pen)</i>"))),
                         htmlOutput("Table.2.1"),conditionalPanel(condition = "input.clustering2 == 'yes'",useShinyalert(), actionButton("btn3.2", "?")),
                         h1(""),
                         plotOutput("Plot.2B.5"), ##############################################################plotOutput("Plot2"), 
                         useShinyalert(),  actionButton("btn3.3", "?"),
                         h1(""),
                         actionButton("go3", "Take a screenshot")))),
             
             tabPanel(strong("Glossary"), 
                      fluidPage(
                        strong("Abundance:"),
                        p("Average number of sea lice per salmon. Users should assume a probable abundance to use this application"),
                        strong("Clustering"),
                        p("If abundances among pens in a farm are assumed to be different so that you want to include the difference in the outputs, you should choose the clustering effect."),
                        strong("Farm: "),
                        p("A farm consists of a group of pens"),
                        strong("ICC (Intraclass correlation coefficient): "), 
                        p("The degree of clustering of sea lice infections in fish within cages. High ICC means that abundance is highly different from pen to pen, while no ICC means that all pens in a farm have exactly same abundance. Maximum ICC that you can choose in this application depends on the abundance that you assume."),
                        strong("Iteration: "),
                        p("How many times the model is simulated to generate the output. Higher number of iterations can generate more accurate estimation, but takes longer time of simulation."),
                        strong("Pen:"),
                        p("An enclosure for fish. A farm consists of multiple pens"),
                        strong("Numbers of selected pens for sampling:"),
                        p("Users can determine from how many pens they sample salmon. When salmon are sampled from partial number of pens, ICC may affect the modelling results"),
                        strong("Lice Limit"),
                        p("Lice limit is a certain level of abundance, which is not supposed to be exceeded by true abundance. The excess will facilitate an instantaneous treatment of sea lice or harvesting of salmon."),
                        strong("Treatment Threshold"),
                        p("If abundance exceeds treatment threshold, then treatment should be applied."),
                        p(""))))
)
