rm(list=ls())
library(shiny); library(reshape2); library(ICC); library(ggplot2); library(ggridges)

ui <-fluidPage(
  img(src="FishSampling.png"),
  navbarPage("",
             tabPanel(strong("HOME"),                      
                      p(""),
                      strong("This tool informs fish sampling strategies, we present an open web-based application which estimates sampling accuracy related to sea louse abundance, given inputs (such as presumed abundance or clustering effect) provided by the user"),
                      p("Scenario 1. How probable does the sampled abundance fall within a certain range with given number of fish to be sampled?"),
                      p("Scenario 2. How probable is the difference in two abundance detected with given number of fish to be sampled?"),
                      p("Scenario 3. How probable is abundance estimated to be correctly against treatment threshold given number of fish to be sampled?"),
                      p(""),
                      p(""),
                      img(src="UPEI Logo_no background.png", height = 130, width = 270),
                      img(src="CERC.png", height = 130, width = 270),
                      img(src="ofi.jpg", height = 130, width = 270),
                      p("Please send any comments, questions or suggestions to Jaewoon Jeong (jjeong@upei.ca)"),
                      p(""),
                      p("R shiny code is available from here, https://github.com/jaewoonjeong/FishSampling"),
                      p("")),
             tabPanel(strong("SCENARIO: 1"), 
                      h4("How probable does the sampled abundance fall within a certain range with given number of fish to be sampled?"),
                      fluidPage(
                        column(4,
                               radioButtons("clustering1B", "Clustering Effect:",c(No = "no", Yes = "yes")),
                               numericInput("iteration.1B","Iteration",value=NULL,min=1,max=100000)),
                        column(4,
                               conditionalPanel(condition = "input.clustering1B == 'no'",selectInput("TotalRange.1B", "Numbers of total sampled fish:",choices = 1:500,multiple = TRUE)),
                               conditionalPanel(condition = "input.clustering1B == 'yes'",selectInput("range.1B", "Numbers of sampled fish per pen:",choices=1:100,multiple = TRUE)),
                               numericInput("u.m","Upper Limit of Abundance:",NULL,min=0,max=10,step=0.01),
                               numericInput("l.m","Lower Limit of Abundance:",NULL,min=0,max=10,step=0.01)),
                        column(4,
                               conditionalPanel(condition = "input.clustering1B == 'yes'",sliderInput("pen.1B", "Number of pens in a farm:", value=NULL, min=1, max=20)),
                               conditionalPanel(condition = "input.clustering1B == 'yes'",selectInput("choice.1B", "Numbers of pens to be sampled:", choices =1:100, multiple = TRUE)))),
                      sidebarLayout(
                        sidebarPanel(width = 4,
                                     conditionalPanel(condition = "input.clustering1B == 'no'",numericInput("ab.1B", "Abundance:", value = NULL, min=0, max=100, step=0.01)),
                                     conditionalPanel(condition = "input.clustering1B == 'yes'",uiOutput("ui.1B.1")),
                                     conditionalPanel(condition = "input.clustering1B == 'yes'",tags$i("The number of abundance must be same to the number of pens in a farm")),
                                     conditionalPanel(condition = "input.clustering1B == 'yes'",strong("Average Abundance of Pens:")),
                                     conditionalPanel(condition = "input.clustering1B == 'yes'",textOutput('Text.1B.1')),
                                     conditionalPanel(condition = "input.clustering1B == 'yes'",strong("ICC:")),
                                     conditionalPanel(condition = "input.clustering1B == 'yes'",textOutput("Text.1B.2")),
                                     conditionalPanel(condition = "input.clustering1B == 'yes'",plotOutput("Plot.1B.2"))),
                        mainPanel(
                          actionButton("goButton.1B", "Go!"),
                          plotOutput("Plot.1B.3"),
                          tableOutput("Table.1B.1")))),
             tabPanel(strong("SCENARIO: 2"), 
                      h4("How probable is the difference in two abundance detected with given number of fish to be sampled?"),
                      fluidPage(
                        column(4,
                               radioButtons("clustering2B", "Clustering Effect:",c(No = "no", Yes = "yes")),
                               numericInput("iteration.2B","Iteration",value=NULL,min=1,max=100000)),
                        column(4,
                               conditionalPanel(condition = "input.clustering2B == 'yes'",selectInput("range.2B", "Numbers of sampled fish per Pen:",choices=1:100,multiple=TRUE)),
                               conditionalPanel(condition = "input.clustering2B == 'no'",selectInput("TotalRange.2B","Numbers of total sampled fish:",choices=1:500,multiple=TRUE))),
                        column(4,
                               conditionalPanel(condition = "input.clustering2B == 'yes'",sliderInput("pen.2B", "Number of pens in a farm:", value=NULL, min=1, max=20)),
                               conditionalPanel(condition = "input.clustering2B == 'yes'",selectInput("choice.2B", "Numbers of pens to be sampled:", choices =1:100, multiple = TRUE)))),
                      sidebarLayout(sidebarPanel(width = 4,
                                                 conditionalPanel(condition = "input.clustering2B == 'no'",numericInput("ab1.2B", "Lower Abundance:", value =NULL, min=0, max=10, step=0.01)),
                                                 conditionalPanel(condition = "input.clustering2B == 'no'",numericInput("ab2.2B", "Higher Abundance:", value =NULL, min=0, max=10, step=0.01)),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",uiOutput("ui.2B.1")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",uiOutput("ui.2B.2")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",tags$i("The number of abundance must be same to the number of pens in a farm")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",strong("Average Lower Abundance of Pens:")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",textOutput('Text.2B.1')),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",strong("Average Higher Abundance of Pens:")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",textOutput('Text.2B.2')),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",strong("ICC1:")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",textOutput("Text.2B.3")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",strong("ICC2:")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",textOutput("Text.2B.4")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",plotOutput("Plot.2B.1")),
                                                 conditionalPanel(condition = "input.clustering2B == 'yes'",plotOutput("Plot.2B.2"))),
                                    mainPanel(
                                      actionButton("goButton.2B", "Go!"),
                                      plotOutput("Plot.2B.3"),
                                      tableOutput("Table.2B.1")))),
             tabPanel(strong("SCENARIO: 3"), 
                      h4("How probable is abundance estimated to be correctly against treatment threshold given number of fish to be sampled?"),
                      fluidPage(
                        column(4,
                               radioButtons("clustering3B", "Clustering Effect:",c(No = "no", Yes = "yes")),
                               numericInput("iteration.3B","Iteration",value=NULL,min=1,max=100000)),
                        column(4,
                               conditionalPanel(condition = "input.clustering3B == 'yes'",selectInput("range.3B", "Numbers of sampled fish per Pen:",choices=1:100,multiple = TRUE)),
                               conditionalPanel(condition = "input.clustering3B == 'no'",selectInput("TotalRange.3B", "Numbers of total sampled fish:",choices = 1:500,multiple = TRUE)), 
                               numericInput("th.3B","Treatment Threshold:",value=NULL,min=0,max=10,step=0.01)),
                        column(4,
                               conditionalPanel(condition = "input.clustering3B == 'yes'",sliderInput("pen.3B", "Number of pens in a farm:", value=NULL, min=1, max=20)),
                               conditionalPanel(condition = "input.clustering3B == 'yes'",selectInput("choice.3B", "Numbers of pens to be sampled:",choices =1:20,multiple = TRUE)))),
                      sidebarLayout(sidebarPanel(width=4,
                                                 conditionalPanel(condition = "input.clustering3B == 'no'",numericInput("ab.3B", "Abundance:", value =NULL, min=0, max=10, step=0.01)),
                                                 conditionalPanel(condition = "input.clustering3B == 'yes'",uiOutput("ui.3B.1")),
                                                 conditionalPanel(condition = "input.clustering3B == 'yes'",tags$i("The number of abundance must be same to the number of pens in a farm")),
                                                 conditionalPanel(condition = "input.clustering3B == 'yes'",strong("Average Abundance of Pens:")),
                                                 conditionalPanel(condition = "input.clustering3B == 'yes'",textOutput('Text.3B.1')),
                                                 conditionalPanel(condition = "input.clustering3B == 'yes'",strong("ICC:")),
                                                 conditionalPanel(condition = "input.clustering3B == 'yes'",textOutput("Text.3B.2")),
                                                 conditionalPanel(condition = "input.clustering3B == 'yes'",plotOutput("Plot.3B.2"))),
                                    mainPanel(
                                      actionButton("goButton.3B", "Go!"),
                                      plotOutput("Plot.3B.1"),
                                      tableOutput("Table.3B.1")))),
             tabPanel(strong("Glossary"), 
                      fluidPage(
                        strong("Abundance:"),
                        p("Number of sea lice per salmon"),
                        strong("Farm: "),
                        p("A farm consists of a group of pens"),
                        strong("ICC (Intraclass correlation coefficient): "), 
                        p("The degree of clustering of sea lice infections in fish within cages. High ICC means that abundance is highly different from pen to pen, while no ICC means that all pens in a farm have exactly same abundance."),
                        strong("Iteration: "),
                        p("How many times the model is simulated to generate the output"),
                        strong("Pen:"),
                        p("An enclosure for fish. A farm consists of multiple pens"),
                        strong("Numbers of pens to be sampled:"),
                        p("Users can determine from how many pens they sample salmon. When salmon are sampled from partial number of pens, ICC may affect the modelling results"),
                        strong("Treatment Threshold"),
                        p("If abundance exceeds treatment threshold, any treatment should be executed to reduce the abundance below the treatment threshold"),
                        p(""))))
  )
